data_path: 'data\predictive_maintenance.csv'
model_directory: 'models\'
## We'll drop Failure Type as it's likely not going to be available to us at prediction time, so it's somewhat of a data leakage issue.
columns_to_drop: ['Product ID', 'Failure Type'] 
columns_to_scale: ['Air temperature [K]','Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]']
columns_to_encode: ['Type']
target_column: 'Target'
param_grid: {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}
