services:
  backend:
    build:
      context: ./back-end  # Adjust according to your directory structure
      dockerfile: Dockerfile
    ports:
      - 5000:5000  # Maps port 5000 on host to port 5000 in the container
    volumes:
      - ./back-end:/app
    environment:
      - FLASK_ENV=development  # Set Flask environment variable
      - MODEL_PATH=/app/models/best_model.pkl
      - CONFIG_PATH=/app/config.yaml
      - MONITOR_PATH=/app/models/model_monitor.pkl
      - FLASK_RUN_PORT=5000  # Set Flask port environment variable
    networks:
      - app-network
    image: josephmcguire/webapp:latest
      
  frontend:
    build: 
      context: ./predictive-maintenance
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./predictive-maintenance:/app
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    networks:
      - app-network
    image: josephmcguire/webapp-frontend:latest


networks:
  app-network:
    driver: bridge