version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/app
    environment:
      - FLASK_ENV=development
      - MODEL_PATH=/app/models/best_model.pkl
      - CONFIG_PATH=/app/config.yaml
      - MONITOR_PATH=/app/models/model_monitor.pkl

  frontend:
    build: ./predictive-maintenance
    ports:
      - "3000:80"
    volumes:
      - ./predictive-maintenance:/app